spring:
  kafka:
    consumer:
      bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
      isolation-level: read_committed
      properties:
        spring.json.trusted.packages: by.pressf.core.*