server:
  port: 50001

spring:
  application:
    name: UserMS
  config:
    import:
      - classpath:application-db.yaml # Database (H2)
      - classpath:application-kafka-consumer.yaml # Kafka Consumer
      - classpath:application-kafka-producer.yaml # Kafka Producer