spring:
  datasource:
    url: jdbc:postgresql://localhost:54321/user_db
    username: test
    password: test
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    url: jdbc:postgresql://localhost:54321/user_db
    user: test
    password: test
    driver-class-name: org.postgresql.Driver