spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092,localhost:9094,localhost:9096
      isolation-level: read_committed
      properties:
        spring.json.trusted.packages: by.pressf.core

dead:
  letter:
    topic:
      name: order-ms-dlt
      transaction-id-prefix: order-ms-dlt-${HOSTNAME:local}-