server:
  port: 50004

spring:
  application:
    name: OrderMS
  config:
    import:
      - classpath:application-db.yaml # Database (H2)
      - classpath:application-kafka-consumer.yaml # Kafka Consumer
      - classpath:application-kafka-producer.yaml # Kafka Producer
      - classpath:kafka-saga-topics.yaml # Commands Topic's